# Generated by Django 5.1.2 on 2024-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medico",
            name="hora_final",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="medico",
            name="hora_inicio",
            field=models.TimeField(default="08:00"),
        ),
    ]
